export const cities = {
  maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Pimpri-Chinchwad",
    "Nashik",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Aurangabad",
    "Navi Mumbai",
    "Solapur",
    "Mira-Bhayandar",
    "Bhiwandi-Nizampur",
    "Jalgaon",
    "Amravati",
    "Nanded-Waghala",
    "Kolhapur",
    "Ulhasnagar",
    "Sangli-Miraj-Kupwad",
    "Malegaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Ichalkaranji",
    "Jalna",
    "Ambarnath",
    "Bhusawal",
    "Panvel",
    "Badlapur",
    "Beed",
    "Gondia",
    "Satara",
    "Barshi",
    "Yavatmal",
    "Achalpur",
    "Osmanabad",
    "Nandurbar",
    "Wardha",
    "Udgir",
    "Hinganghat",
  ],
  telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Khammam",
    "Karimnagar",
    "Ramagundam",
    "Mahabubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
    "Siddipet",
    "Jagtial",
    "Mancherial",
    "Armoor",
  ],
};

export default cities;
